### ISSUE TITLE
PdfBook: creation fails on windows if upload directory contains spaces

### ISSUE THREAD

**Issue by rsudev** [OrganicDesign/extensions#10]
If the $wgUploadDirectory contains spaces (on windows), the commandline for htmldoc and the output redirection does not work.

**Comment by rsudev** [comment]
escaping $file and $cache like
```
$cmd  = "htmldoc -t pdf --charset $charset $options $cmd \"$file\" ";
putenv( "HTMLDOC_NOCGI=1" );
shell_exec( "$cmd > \"$cache\" " );
```
works for me

**Comment by Aranad** [comment]
Oops yeah that's not good form, that would fail on Linux too, quotes added now.
