### ISSUE TITLE
PdfBook.php missing

### ISSUE THREAD

**Issue by ravage84** [OrganicDesign/extensions#19]
Pdfbook.php is missing at https://github.com/OrganicDesign/extensions/tree/94028e35acd05c5e80fdea7027c3f4b3f81d9e0b/MediaWiki/PdfBook

Which makes it impossible to install or update the extension.

I came here from https://www.mediawiki.org/wiki/Extension:PdfBook, by the way.

**Comment by Aranad** [comment]
Please use the master branch as it's not reliable pre MediaWiki 1.25. For 1.25+ the PdfBook.php file is unnecessary as you should be using wfLoadExtension.
