### ISSUE TITLE
greek utf8 not showing

### ISSUE THREAD

**Issue by edrimon** [OrganicDesign/extensions#20]
![screenshot](https://cloud.githubusercontent.com/assets/1180528/19075080/091daf0c-8a4c-11e6-9569-70ee4034f4a1.png)

UTF8 greek are shown as in the attached

**Comment by Aranad** [comment]
Sorry but HTMLDOC, the underlying library used to convert to PDF, doesn't have good UTF8 support.

**Comment by edrimon** [comment]
Shouldn't you mention this important detail? I lost valuable time..

**Comment by Aranad** [comment]
I've added a note to the MW extension page.
