### ISSUE TITLE
Folders do not expand in TreeAndMenu version 4.2.1, MediaWiki 1.30.0

### ISSUE THREAD

**Issue by qm2k** [OrganicDesign/extensions#34]
Tree looks like this for me after migration:
![screenshot from 2018-01-31 12 38 22 cropped](https://user-images.githubusercontent.com/13719792/35615875-826716b8-0684-11e8-8389-c4403c9022a0.png)

Click selects it like this:
![screenshot from 2018-01-31 12 42 58 cropped](https://user-images.githubusercontent.com/13719792/35615889-8b7fcefc-0684-11e8-8ef8-a8954bdc6e0a.png)
but it does not expand.

On a previous version it looked like this:
![screenshot from 2018-01-31 12 38 19 cropped](https://user-images.githubusercontent.com/13719792/35615724-198d238a-0684-11e8-82c8-98294b2c340d.png)

Here's the source code:
```
{{#tree: root=/ | openlevels=9 |
* Каталог
** Каталоги/Контрагенты/Проекты
*** ...
** Поручения/Задачи/Совещания
}}
```

Here's what web console shows:
![screenshot from 2018-01-31 12 51 42 redacted](https://user-images.githubusercontent.com/13719792/35616307-efe57dd2-0685-11e8-8c9a-2c747e388597.png)
Clicks do not produce new lines in console.

What am I doing wrong?

**Comment by Aranad** [comment]
What do you mean "on previous version it looked like this"? did you upgrade the tree extension or the wiki?

**Comment by AnthillBeetle** [comment]
Both. I installed new wiki, installed latest version of extension on it, then copied all pages.

**Comment by qm2k** [comment]
Both. I installed new wiki, installed latest version of extension on it, then copied all pages.

**Comment by Aranad** [comment]
It may be an issue with MW1.30, I'll be upgrading a wiki to 1.30 in the next day or two and will upgrade the tree extension if it doesn't work on it.

**Comment by qm2k** [comment]
Thank you, will be waiting for the results.

**Comment by Aranad** [comment]
There's no incompatibility between TreeAndMenu and MW1.30, try disabling other 3rd party extensions to see if there's a conflict there.

**Comment by Aranad** [comment]
oh wait, I spoke to soon - it seems that there is an issue... it only works on special pages but has the problem you've reported on content pages.

**Comment by Aranad** [comment]
Ok I found the problem, TreeAndMenu 4.2.2 should work for you. MediaWiki 1.30 has a new parser option called wrapClass which wraps the parsed output in the tree nodes in divs that the fancyTree component doesn't like. I've called setWrapOutputClass( false ) if the method exists in the parserOptions object.

**Comment by qm2k** [comment]
Yes, it all works now (needed to re-save the page). Thank you for super-speedy fix!

**Comment by Aranad** [comment]
no problem 👍
