### ISSUE TITLE
TreeAndMenu: Use local jquery instead of online

### ISSUE THREAD

**Issue by gioulisapo** [OrganicDesign/extensions#35]
Is it possible instead of loading the online version jquery to have a local copy of it in the wiki? If I am offline the sidebar does not appear and hangs whilst w8ing for the jquery to load. 

Could you please offer some pointers as to how to achieve that? Thank you very much!!!!

**Comment by Aranad** [comment]
You must have another extension loading an external jQuery, TreeAndMenu expects jQuery to already be present.
