### ISSUE TITLE
Fix for icons in TreeAndMenu 

### ISSUE THREAD

**Issue by Contrafibularity** [OrganicDesign/extensions#4]
fancytree.css apparently assumes that MediaWiki's directory is called 'wiki'. If this is not the case, the icons will not appear. Of course, amending

  url("/wiki/extensions/TreeAndMenu/fancytree/icons.gif");

to

  url(' extensions/TreeAndMenu/fancytree/icons.gif');
(single quotes?)

should do the trick

**Comment by Aranad** [comment]
Oh yeah thanks I forgot about that - I had to put that path there for it to work when the CSS was loaded with the resource loader, but I'm not using resource loader for the CSS now, so it doesn't need any path since icons.gif is in the same folder. Should work now :-)

**Comment by Contrafibularity** [comment]
Thanks!
