### ISSUE TITLE
EmailPage / Database error while sending the e-mails

### ISSUE THREAD

**Issue by kghbln** [OrganicDesign/extensions#5]
Query:
```text
SELECT user_name,up_value FROM `rg_user` LEFT JOIN `rg_user_properties` ON ((user_id = up_user) AND up_property = 'gender') WHERE user_name = 'DFRV - Regionalgruppe Berlin'
```
Function:
 `GenderCache::doQuery/MediaWikiTitleCodec::getNamespaceName`

Error:
`0` 

Admittedly I am using a silighly out of date version 2.3.3, 2015-03-05 on MW 1.23.10 with PHP 5.4.45 (cgi-fcgi) and MySQL 5.1.73-log

**Comment by Aranad** [comment]
I don't know what to do about that, the query has a syntax error in it (extra bracket), but it's not in my code...

**Comment by kghbln** [comment]
@Aranad Thanks for your fast reply and assessment. I have just reported this on [Phabriacator](https://phabricator.wikimedia.org/T115789). Let's see where we go from here. Closing this one for now.
